In [1]:
import tensorflow as tf

In [2]:
batch_size = 20

In [ ]:
songlength = 100

In [3]:
NUM_FEATURES_PER_TONE = 3

In [4]:
tones_per_cell = 1

In [5]:
num_song_features = NUM_FEATURES_PER_TONE*tones_per_cell+1

In [17]:
songlength = 4

In [18]:
input_songdata = tf.placeholder(shape=[batch_size, songlength, num_song_features], dtype=tf.float32)

In [19]:
input_songdata

<tf.Tensor 'Placeholder:0' shape=(20, 4, 4) dtype=float32>

In [27]:
hidden_size_g = 350
num_layers_g = 2
keep_prob = 0.5

In [28]:
with tf.variable_scope('G') as scope:
    lstm_cell = tf.nn.rnn_cell.BasicLSTMCell(hidden_size_g, forget_bias=1.0, state_is_tuple=True)
    lstm_cell = tf.nn.rnn_cell.DropoutWrapper(lstm_cell, output_keep_prob=keep_prob)
    cell = tf.nn.rnn_cell.MultiRNNCell([lstm_cell] * num_layers_g, state_is_tuple=True)

In [32]:
initial_state = cell.zero_state(batch_size, tf.float32)

In [33]:
state = initial_state

In [35]:
random_input_scale=1.0

In [36]:
random_rnninputs = tf.random_uniform(shape=[batch_size, songlength, int(random_input_scale*num_song_features)], minval=0.0, maxval=1.0, dtype=tf.float32)

In [37]:
random_rnninputs

<tf.Tensor 'random_uniform:0' shape=(20, 4, 4) dtype=float32>

In [38]:
import numpy as np

In [39]:
ss = tf.Session()

In [41]:
teste = ss.run(random_rnninputs)

In [42]:
teste.shape

(20, 4, 4)

In [43]:
teste[0]

array([[ 0.81155038,  0.89210057,  0.79234672,  0.85448825],
       [ 0.02508581,  0.93683541,  0.4361738 ,  0.88169479],
       [ 0.31208444,  0.514817  ,  0.06167626,  0.18198204],
       [ 0.77786887,  0.6602006 ,  0.81442714,  0.32397187]], dtype=float32)

In [44]:
teste[1]

array([[ 0.45934784,  0.44715381,  0.43608534,  0.56029177],
       [ 0.90066063,  0.16616642,  0.97424364,  0.99868333],
       [ 0.4224757 ,  0.57235265,  0.06112874,  0.28408682],
       [ 0.33587575,  0.95023203,  0.75589108,  0.80220258]], dtype=float32)

In [80]:
teste2 = tf.placeholder("float", [5,30])

In [81]:
for in range(5,30):

range(5, 30)

In [ ]:
x = tf.constant([35, 40, 45], name='x')

In [84]:
[for a in range(10)]

SyntaxError: invalid syntax (<ipython-input-84-e200cf186b6f>, line 1)

In [ ]:
import tensorflow as tf

x = tf.placeholder("float", [None, 3])
y = x * 2

with tf.Session() as session:
    x_data = [[1, 2, 3],
              [4, 5, 6],]
    result = session.run(y, feed_dict={x: x_data})
    print(result)

In [70]:
teste1 = tf.random_uniform([5,30])

In [73]:
teste2 = teste1

In [74]:
ss.run(teste1)

array([[ 0.44025469,  0.09309399,  0.09786725,  0.94217277,  0.89799368,
         0.77859926,  0.39995241,  0.2877692 ,  0.82183659,  0.30455041,
         0.78627598,  0.14717031,  0.82652593,  0.32420444,  0.98970044,
         0.68351841,  0.85633016,  0.76893365,  0.23560524,  0.58562636,
         0.05717468,  0.50096929,  0.08221233,  0.55158532,  0.56246674,
         0.69647634,  0.26964128,  0.11939597,  0.27517211,  0.23409271],
       [ 0.53022361,  0.34294271,  0.6195395 ,  0.60983849,  0.88040471,
         0.38760602,  0.04695678,  0.89107108,  0.71265519,  0.10662997,
         0.50385547,  0.19018996,  0.50365293,  0.08469093,  0.75373709,
         0.36072707,  0.21947098,  0.47711217,  0.68416452,  0.89364719,
         0.13202775,  0.49624336,  0.65328014,  0.13917136,  0.61090922,
         0.85396373,  0.06618297,  0.412606  ,  0.97426701,  0.11540937],
       [ 0.32250261,  0.97263324,  0.72087932,  0.79750645,  0.3306973 ,
         0.09176517,  0.8394556 ,  0.21549332,  0

In [79]:
ss.run(teste2)

array([[ 0.94863808,  0.49221528,  0.13022494,  0.19942498,  0.52389979,
         0.76693428,  0.23207319,  0.82114792,  0.44259083,  0.9349848 ,
         0.80071199,  0.12967682,  0.61496925,  0.44067919,  0.68202591,
         0.44312918,  0.47657907,  0.51429176,  0.26793194,  0.83430159,
         0.22755003,  0.73437321,  0.03392529,  0.69811141,  0.12957704,
         0.8992883 ,  0.72275722,  0.18179345,  0.25813508,  0.44128335],
       [ 0.10012829,  0.97789729,  0.71870577,  0.86062253,  0.25910115,
         0.9528451 ,  0.72336411,  0.62126613,  0.65867114,  0.50210309,
         0.94425845,  0.35850322,  0.18942487,  0.80731332,  0.73568273,
         0.04830587,  0.6932354 ,  0.08371329,  0.47213948,  0.14474225,
         0.44521523,  0.49885845,  0.84267414,  0.00825989,  0.98895991,
         0.53187525,  0.97922933,  0.7668072 ,  0.60289264,  0.81667852],
       [ 0.70259881,  0.45367002,  0.19440985,  0.36535263,  0.74238789,
         0.537009  ,  0.04363036,  0.66548526,  0

In [61]:
split0, split1, split2 = tf.split(teste1, [4, 15, 11], 1)

In [64]:
ss.run(split0),ss.run(split1),ss.run(split2)

(array([[ 0.29930532,  0.63005197,  0.29715085,  0.682253  ],
        [ 0.44510818,  0.69516313,  0.28326786,  0.83559215],
        [ 0.42886531,  0.33150721,  0.34210789,  0.55084729],
        [ 0.96988237,  0.96135402,  0.97657335,  0.39346671],
        [ 0.94685793,  0.40960705,  0.5885241 ,  0.3326906 ]], dtype=float32),
 array([[ 0.01985538,  0.45304859,  0.28868532,  0.57504034,  0.60963464,
          0.32098639,  0.41572857,  0.94849348,  0.00829279,  0.66650486,
          0.88673401,  0.15996158,  0.49561584,  0.53517473,  0.23586977],
        [ 0.93677402,  0.82977235,  0.98640418,  0.27248323,  0.56018579,
          0.4266603 ,  0.51054037,  0.64523852,  0.41462541,  0.82327306,
          0.25631034,  0.53815401,  0.75665164,  0.76759219,  0.28012919],
        [ 0.20459235,  0.54845858,  0.82371235,  0.6105938 ,  0.28994727,
          0.43985462,  0.99971831,  0.00593019,  0.13934052,  0.55547333,
          0.10600293,  0.55561757,  0.76044846,  0.78642654,  0.42143631],
    